
all: server client parent_child_conflict udp_server udp_client unix_server unix_client simple_telnet_server

unix_server: unix_server.c

unix_client: unix_client.c

udp_client: udp_client.c

udp_server: udp_server.c

server: server.c

parent_child_conflict: parent_child_conflict.c

client: client.c

simple_telnet_server: simple_telnet_server.c

